version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./token.env

    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/src:/app/src
      - /app/node_modules

    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

    networks:
      - app-network

    restart: unless-stopped

networks:
  app-network:


